version: '3'
services:
  zenn:
    build:
      context: .
      dockerfile: ../Dockerfile
    #command: /home/codespace/.nodejs/current/bin/npm install zenn-cli@latest && /home/codespace/.nodejs/current/bin/npx zenn preview
    volumes:
      - ../:/zenn
    ports:
      - 8000:8000
